### ISSUE TITLE
Fehler beim Aufruf der Benutzergruppen

### ISSUE THREAD

**Issue by arboc** [heimrichhannot/contao-youtube-bundle#2]
>Attempted to load interface "ConfigElementType" from namespace "HeimrichHannot\ReaderBundle\ConfigElementType".
Did you forget a "use" statement for another namespace?

![image](https://user-images.githubusercontent.com/4447843/51600313-f35e9080-1f01-11e9-9f9f-9d17b3e15e32.png)

Ich würde sagen, hier wurde die Abhängigkeit zum `heimrichhannot/contao-reader-bundle` nicht in der composer.json aufgenommen. Leider liegt das Bundle nur als Beta vor, so dass beim hinzufügen den Fehler gibt:

>   Could not find a version of package heimrichhannot/contao-reader-bundle mat ching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by Defcon0** [comment]
Kannst du bitte mal probieren, die `use`s gegen absolute Angaben auszutauschen, d.h.

`class YoutubeReaderConfigElementType implements \HeimrichHannot\ReaderBundle\ConfigElementType\ConfigElementType`

und analog die anderen Klassen-Nutzungen. Es kann sein, dass dann evtl. der Autoloader nicht zuschlägt.

**Comment by arboc** [comment]
Das Interface existiert nicht in dem Paket....
Es liegt im im ReaderBundle (_\HeimrichHannot\\**ReaderBundle**\ConfigElementType\ConfigElementType_). Da hilft auch die absolute Angabe des Namespaces nicht (habe ich probiert).

Übrigens gibt es hier noch mehr Verweise auf das ReaderBundle in der Datei (YoutubeReaderConfigElementType.php) :

```php
use HeimrichHannot\ReaderBundle\ConfigElementType\ConfigElementType;
use HeimrichHannot\ReaderBundle\Item\ItemInterface;
use HeimrichHannot\ReaderBundle\Model\ReaderConfigElementModel;
```

**Comment by Defcon0** [comment]
Das ist mir schon bewusst. Es hätte bloß sein können, dass dann der Autoloader nicht zuschlägt und eine Warning ausgibt. In Funktionen-Blöcken ist es bspw. so. Scheinbar aber nicht bei der Deklaration von Klassen.

Da mir aktuell etwas die Zeit fehlt, könntest du bitte noch folgendes probieren, d.h. einfach die Klasse  `YoutubeReaderConfigElementType` mit diesem Code ersetzen (ist zwar nicht die beste Lösung; eigentlich müsste man das in ein eigenes Modul herausziehen; aber immerhin würde es dann wieder funktionieren):

```
<?php

/*
 * Copyright (c) 2019 Heimrich & Hannot GmbH
 *
 * @license LGPL-3.0-or-later
 */

namespace HeimrichHannot\YoutubeBundle\ConfigElementType;

use Contao\CoreBundle\Framework\ContaoFrameworkInterface;
use Contao\FrontendTemplate;
use Contao\System;
use HeimrichHannot\YoutubeBundle\Configuration\ConfigFactory;

if (class_exists('\HeimrichHannot\ReaderBundle\HeimrichHannotContaoReaderBundle'))
{
    class YoutubeReaderConfigElementType implements \HeimrichHannot\ReaderBundle\ConfigElementType\ConfigElementType
    {
        const TYPE = 'youtube';

        /**
         * @var ContaoFrameworkInterface
         */
        private $framework;

        public function __construct(ContaoFrameworkInterface $framework)
        {
            $this->framework = $framework;
        }

        public function addToItemData(\HeimrichHannot\ReaderBundle\Item\ItemInterface $item, \HeimrichHannot\ReaderBundle\Model\ReaderConfigElementModel $readerConfigElement)
        {
            if (!$item->getRawValue($readerConfigElement->youtubeSelectorField)) {
                return;
            }

            if ((!$youtubeData = $item->getRawValue($readerConfigElement->youtubeField)) || empty($youtubeData)) {
                return;
            }
            $configData = [
                'type' => 'youtube',
                'addYouTube' => true,
                'youtube' => $youtubeData,
                'autoplay' => $readerConfigElement->autoplay,
            ];

            $video = System::getContainer()->get('huh.youtube.videocreator')->createVideo(ConfigFactory::CONTEXT_LIST_BUNDLE, array_merge($item->getRaw(), $configData));
            $template = new FrontendTemplate();
            $video->addToTemplate($template);
            $templateData = $template->getData();
            $item->setFormattedValue('youtubeVideos', [$readerConfigElement->youtubeField => (array) $templateData['youtube']]);
        }
    }

}
```

Alternativ könntest du natürlich auch deine Minimum-Stability heruntersetzen und das reader-bundle ganz normal installieren.

**Comment by arboc** [comment]
Grundsätzlich müsste die Abhängigkeit zum ReaderBundle erst mal in der composer.json eingetragen werden....

Dein Workaround greift nicht.... 
1. Die Klasse wird nicht mehr gefunden, wird in der dca aufgerufen
1. Auch bei YouTubeListConfigElementType.php gibt es einen ähnlichen Fehler.

Anbei etwas was, funktioniert (beide Dateien wurden angepasst):  
[ConfigElementType.zip](https://github.com/heimrichhannot/contao-youtube-bundle/files/2787806/ConfigElementType.zip)

**Comment by Defcon0** [comment]
> Grundsätzlich müsste die Abhängigkeit zum ReaderBundle erst mal in der composer.json eingetragen werden....

Genau das ist aber nicht der Fall. Das Reader-Bundle ist sozusagen eine Soft-Dependency, d.h., wenn sie da ist, hat sie Nutzen von den Klassen, wenn nicht, ist es aber auch kein Problem. Das Muster dafür ist "graceful degredation".

Ich gebe dir Recht, besser wäre das Auslagern in ein eigenes Bundle. Das haben wir bei anderen Dingen auch schon gemacht, siehe bspw. https://github.com/heimrichhannot/contao-slick-reader-bundle . Mir fehlt aber aktuell einfach die Zeit, das auszulagern.

Der Workaround scheint aber dann doch zu funktionieren. Die ClassNotFound-Exception wird nicht mehr geworfen, wenn man das ganze mit class_exists() kapselt, richtig?

Bzgl. des list-bundles ist es dieselbe Sache, richtig.

Du sagst, in der DCA wird es aufgerufen. Hier wird aber geprüft, ob das reader bundle drauf ist, d.h. hier sollte es keine Probleme geben:

```
if (\Contao\System::getContainer()->get('huh.utils.container')->isBundleActive('HeimrichHannot\ReaderBundle\HeimrichHannotContaoReaderBundle')) {

```

Wenn du deine beiden Klassen nutzt, hast du dann noch Probleme? Falls nicht, würde ich es so einchecken und beide Klassen bei Gelegenheit herausziehen.

**Comment by Defcon0** [comment]
Ah, ich hab gerade noch den else-Zweig in deinen Dateien gesehen. Ohne diesen geht es tatsächlich nicht? Der Code im DCA sollte, wie gesagt, kein Problem bei dir sein, weil der Interpreter dort gar nicht reinläuft, weil das Reader-Bundle nicht bei dir installiert ist.

**Comment by arboc** [comment]
ohne `else` gibt es einen Fehler, dass die Klasse nicht gefunden wird (autoloader wollte die haben).
Daher die Klasse noch mal nur mit der Konstanten. Die Abfrage nach dem ReaderBundle inder dca hatte ich übersehen.

**Comment by Defcon0** [comment]
Fixed in https://github.com/heimrichhannot/contao-youtube-bundle/tree/3.1.2

Bitte teste mal, ob es so jetzt für dich passt. Danke!

**Comment by arboc** [comment]
passt, Danke! 🥇
