### ISSUE TITLE
alertifyjs not defined

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-youtube-bundle#4]
Hallo,

ich habe die Erweiterung vor einiger Zeit eingesetzt und nach der jetzigen Installation hat leider nicht mehr funktioniert, da sich viele CSS-Klassen geändert haben und auch Javascript nicht gefunden wurde. Die Links in der Doku führten auch nicht zum Ziel, so dass ich die Fehlermeldungen ausgewertet habe und darauf gekommen bin https://alertifyjs.com/ einzubinden.

Könnte bitte jemand die Dokumentation aktualisieren. Vielen Dank.

**Comment by Defcon0** [comment]
Nutzt du die Einbindung des JacaScripts über Webpack/Encore oder Contao's $GLOBALS['TL_JAVASCRIPT']?

**Comment by operatorone** [comment]
Ich habe das JS manuell über ein j_template.html5 umgesetzt. 

`$GLOBALS['TL_JAVASCRIPT'][] = '/files/theme/js/alertify.min.js|static';`

**Comment by Defcon0** [comment]
Das Problem bzgl. alertify ist in Version 3.3.0 behoben und sollte nun in Webpack/Encore- sowie auch in Umgebungen ohne Tool-Support ($GLOBALS) funktionieren. Kannst du es bitte ausprobieren? Vielen Dank!

Das Problem war, dass alertify eigentlich hätte mitgeliefert werden müssen. Das ist jetzt nachgeholt. Du kannst damit also das alertify in deinem theme-Ordner löschen.

**Comment by operatorone** [comment]
Moin, ich habe die Erweiterung aktualisiert und alle manuellen Einbindungen entfernt. Sieht aus, als würde es jetzt gut funktionieren. Lieben Dank für die Mühe.
