### ISSUE TITLE
Anzeige "More Videos" und "Ähnliche Videos" obwohl Option deaktiviert ist

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-youtube-bundle#5]
Obwohl die Option "Ähnliche Videos" deaktiviert wurde, werden während der Pause "Mehr Videos" und am Ende des Clips "Ähnliche Videos" angezeigt. Muss ich hier noch etwas im Template anpassen oder ist diese Option für etwas anderes zuständig?

Viele Grüße,
operatorone

![optionen](https://user-images.githubusercontent.com/4036452/54610174-bf60a100-4a54-11e9-810f-c6f7366a85bb.jpg)
![related-videos](https://user-images.githubusercontent.com/4036452/54610175-bf60a100-4a54-11e9-8126-b9c655785744.jpg)
![more-videos](https://user-images.githubusercontent.com/4036452/54610177-bf60a100-4a54-11e9-96a6-99a67edc231b.jpg)

**Comment by Defcon0** [comment]
"Ähnliche Videos" ist der "rel"-Parameter des YouTube-Embeds. Die Bedeutung dieses Parameters hat sich September 2018 verändert:

https://stackoverflow.com/questions/48386252/youtube-iframe-api-parameter-rel-0-doesnt-work/52918387

Ich habe die Beschriftung der Checkbox im neuen Release mal entsprechend angepasst.

**Comment by operatorone** [comment]
Hi, ich habe mal beide Einstellungen ausprobiert und erhalte folgende Parameter in den iFrames:

`<iframe src="//www.youtube-nocookie.com/embed/oCfwVpEjjgg?rel=1&amp;modestbranding=1&amp;showinfo=0&amp;autoplay=1" data-src="//www.youtube-nocookie.com/embed/oCfwVpEjjgg?rel=1&amp;modestbranding=1&amp;showinfo=0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>`

`<iframe src="//www.youtube-nocookie.com/embed/oCfwVpEjjgg?rel=0&amp;modestbranding=1&amp;showinfo=0&amp;autoplay=1" data-src="//www.youtube-nocookie.com/embed/oCfwVpEjjgg?rel=0&amp;modestbranding=1&amp;showinfo=0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>`

Das `?rel=` wird zwar korekt gesetzt, hat aber leider keinerlei Auswirkung auf die Anzeige von "Ähnliche Videos" am Ende oder "Weitere Videos" während der Pause.

**Comment by Defcon0** [comment]
Ich habe es gerade getestet mit dem YouTube-Video der ID "oCfwVpEjjgg". Aktiviere ich den rel-Parameter, werden mir querbeet Videos empfohlen. Nehme ich das Häkchen heraus, bekomme ich nur Videos vom Channel, dem das Video angehört. Letzteren Fall habe ich mal in den Anhang gepackt.

![screen](https://user-images.githubusercontent.com/1485098/54703330-e1335400-4b38-11e9-819e-d2e4003bbac4.png)
![screen2](https://user-images.githubusercontent.com/1485098/54703331-e1335400-4b38-11e9-9b68-96c5c890665c.png)
