### ISSUE TITLE
Fehlermeldung bei Installation in Contao 4.8.5

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-youtube-bundle#6]
Ich erhalte bei Versuch die Erweiterung in Contao 4.8.5 zu installieren folgende Meldung im Contao Manager:

> $ /usr/bin/php7.3-cli -q -d memory_limit=-1 /homepages/15/XXXXX/htdocs/XXXXX/web/contao-manager.phar.php composer require heimrichhannot/contao-youtube-bundle --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
> 
> Using version ^3.5 for heimrichhannot/contao-youtube-bundle
> /homepages/15/XXXXX/htdocs/XXXXX/composer.json has been updated
> 
> # Process terminated with exit code 0
> # Result: OK
> 
> > Resolving dependencies using Composer Cloud v2.1.1
> 
> # Job ID 6WNNzhVYPvKgejxzWGFwpKClihBwSiecxrsewrP5D55jdZDCaRiTBfjX5OLLl1529aREu3BarJJQ5KX7DO8Jg1r completed in 26 seconds
> # Memory usage: 417.53MB (peak: 1995.5MB), time: 26.37s.
> 
> $ /usr/bin/php7.3-cli -q -d memory_limit=-1 /homepages/15/XXXXX/htdocs/XXXXX/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader
> 
> ocramius/package-versions: Generating version class...
> ocramius/package-versions: ...done generating version class
> contao/manager-plugin: Generating plugin class...
> contao/manager-plugin: ...done generating plugin class
> 
> In DefinitionErrorExceptionPass.php line 54:
>                                                                                
>   Cannot autowire service "huh.youtube.videocreator": argument "$configFactor  
>   y" of method "HeimrichHannot\YoutubeBundle\Video\VideoFactory::__construct(  
>   )" references class "HeimrichHannot\YoutubeBundle\Configuration\ConfigFacto  
>   ry" but no such service exists. You should maybe alias this class to the ex  
>   isting "huh.youtube.configurator" service.                                   
>                                                                                
> 
> Loading composer repositories with package information
> Installing dependencies from lock file
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
> Package operations: 2 installs, 0 updates, 0 removals
>   - Installing heimrichhannot-contao-components/alertifyjs (1.11.2): Loading from cache
>   - Installing heimrichhannot/contao-youtube-bundle (3.5.2): Loading from cache
> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
> Generating optimized autoload files
> > Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
> Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
> 
> In ScriptHandler.php line 88:
>                                                                                
>   An error occurred while executing the "contao:install-web-dir" command:      
>   In DefinitionErrorExceptionPass.php line 54:                                 
>                                                                                
>                                                                                
>     Cannot autowire service "huh.youtube.videocreator": argument "$configFact  
>   or                                                                           
>     y" of method "HeimrichHannot\YoutubeBundle\Video\VideoFactory::__construc  
>   t(                                                                           
>     )" references class "HeimrichHannot\YoutubeBundle\Configuration\ConfigFac  
>   to                                                                           
>     ry" but no such service exists. You should maybe alias this class to the   
>   ex                                                                           
>     isting "huh.youtube.configurator" service.                                                                                                          
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]
> 
> # Process terminated with exit code 1
> # Result: General error
> 
> ---
> 
> ### Der Hintergrundprozess wurde unerwartet beendet ###

**Comment by AlexejKossmann** [comment]
Ich hab gerade die Version 3.6.1 veröffentlicht, probiere bitte ob es bereits das Problem behoben hat.

**Comment by operatorone** [comment]
Scheint funktioniert zu haben. Vielen Dank. Ich konfiguriere jetzt noch die Erweiterung und falls noch was auftaucht, gebe ich bescheid.
