### ISSUE TITLE
Keine Einstellungen in root page (Contao 4.9)

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-youtube-bundle#7]
Hallo,

ich habe die Erweiterung in ein Contao 4.9-System installiert und leider finde ich in der root page keine Möglichkeit mehr die provacy settings einzustellen. Hat sich hier etwas in der Bedienung geändert oder ist das ggf. eine Inkompatibiliät mit Contao 4.9?

Viele Grüße,
operatorone

**Comment by koertho** [comment]
@operatorone Das liegt daran, dass bei Contao 4.9 eine neue root-page-palette eingeführt wurde. Sollte schnell zu beheben sein.

**Comment by koertho** [comment]
@operatorone Should be fixed in 3.7.1.
