### ISSUE TITLE
Warning in Contao 4.9

### ISSUE THREAD

**Issue by koertho** [heimrichhannot/contao-youtube-bundle#8]
On cache warmup there is a `Warning: array_key_exists() expects parameter 2 to be array, null given`,

The errors seems to be relatef to core fields used by youtube bunde (checked for tl_content.autoplay) but not exist anymore in contao 4.9

**Comment by plorenz-etes** [comment]
I second this problem

**Comment by koertho** [comment]
@plorenz-etes Should be fixed in version 3.7.9. Can you confirm this?

**Comment by plorenz-etes** [comment]
Indeed - it is fixed now, thank you!
