### ISSUE TITLE
Kein Modal/Video bei "Erweiterten Datenschutzmodus"

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-youtube-bundle#9]
Hallo, wenn ich in der Wurzelseite "Erweiterten Datenschutzmodus aktivieren" anklicke und das Default-Template auswähle, habe ich auf der Seite mit dem Player nur noch ein Vorschaubild und das Modal wird beim Klick auf das Bild nicht ausgelöst.

Ich bekomme im Firefox auch folgende Meldungen in der Console:
`Feature Policy: Unbekannte Funktionalität (Feature) "accelerometer" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "autoplay" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "encrypted-media" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "gyroscope" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "picture-in-picture" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "accelerometer" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "autoplay" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "encrypted-media" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "gyroscope" wird ignoriert.
Feature Policy: Unbekannte Funktionalität (Feature) "picture-in-picture" wird ignoriert.`

Beispiel: https://www.systemisch-positive-praxis-koeln.de/beispiel/

Ich habe zusätzlich noch heimrichhannot-contao-components/alertifyjs isntalliert. Hat aber auch leider keinen Erfolg gebracht.

Wenn ich die Checkbox "Erweiterten Datenschutzmodus aktivieren" aus lasse, wird das Video ganz normal abgespielt.

**Comment by operatorone** [comment]
Gibt es dazu irgendeine Idee?

**Comment by project-cc** [comment]
Nach dem Update von 4.4.x auf Contao 4.9.x funktioniert die Erweiterung (Version 3.7.3) nicht mehr.  Das Video lässt sich nur noch ohne Datenschutzeinstellungen und ohne Vorschaubild aufrufen. Gibt es einen Workaround oder Lösung?

**Comment by operatorone** [comment]
Gibt es hier schon Neuigkeiten?

**Comment by operatorone** [comment]
Gibt es hier schon einen Fix?

**Comment by koertho** [comment]
Hi, wenn möglich nutze bitte unser [Video-Bundle](https://github.com/heimrichhannot/contao-video-bundle). Das ist mit Contao 4.9 getestet, verfügt aber leider noch nicht über alle Funktionen und ist (noch) nicht Datenbank-Kompatibel. Wenn dir das aussreicht, sollten deine Probleme schon behoben sein ;)

**Comment by koertho** [comment]
Ansonsten könnte es an gesperrten Cookies oder blockenden Scripts liegen (Cookiebot im Einsatz?)

**Comment by operatorone** [comment]
Hi, ich habe keinen Cookiebot auf der Seite im Einsatz. Da sollte nichts Skripte blockieren. Das Video-Bundle kann ich gerne mal testen. Welche Funktionen gingen denn hier noch nicht?

**Comment by koertho** [comment]
Hauptsächlich fehlt aktuell das automatische Laden von Vorschaubildern von YouTube, ebenso werden Events noch nicht unterstützt.

**Comment by operatorone** [comment]
Wäre es denn möglich ein eigenes Vorschaubild einzusetzen? Events fände ich grade nicht so wichtig. Hauptsache der DSGVO-Prozess ist abgedeckt.

**Comment by koertho** [comment]
Manuelle Vorschaubilder sind möglich. Teste es einfach mal 😉
